imageType:
    Original: {}
    # Wavelet: {}
    # LoG: {"sigma": [1.0, 3.0, 5.0]}

setting:
  binWidth: 1
  resampledPixelSpacing:
  additionalInfo: False

featureClass:
  firstorder:
  glrlm:
  glszm:
  gldm:
  ngtdm: